#!/usr/bin/env python3
"""Generate worlds/fleet.sdf and config/fleet.rviz from config/fleet.yaml.

One source of truth for the fleet: edit fleet.yaml, run this, and the Gazebo
world, RViz layout, launch file, and pipeline all agree on robot ids/poses.
"""
from pathlib import Path
from typing import Any

import yaml

ROOT = Path(__file__).resolve().parent.parent

WORLD_HEADER = """<?xml version="1.0" ?>
<!-- AUTO-GENERATED by scripts/generate_fleet.py from config/fleet.yaml. Do not edit. -->
<sdf version="1.8">
  <world name="fleet">

    <plugin filename="gz-sim-physics-system" name="gz::sim::systems::Physics"/>
    <plugin filename="gz-sim-scene-broadcaster-system" name="gz::sim::systems::SceneBroadcaster"/>
    <plugin filename="gz-sim-user-commands-system" name="gz::sim::systems::UserCommands"/>

    <light name="sun" type="directional">
      <cast_shadows>true</cast_shadows>
      <pose>0 0 10 0 0 0</pose>
      <diffuse>0.8 0.8 0.8 1</diffuse>
      <specular>0.2 0.2 0.2 1</specular>
      <direction>-0.5 0.1 -0.9</direction>
    </light>

    <model name="ground_plane">
      <static>true</static>
      <link name="link">
        <collision name="collision">
          <geometry>
            <plane><normal>0 0 1</normal><size>100 100</size></plane>
          </geometry>
          <surface>
            <friction><ode><mu>100</mu><mu2>50</mu2></ode></friction>
          </surface>
        </collision>
        <visual name="visual">
          <geometry>
            <plane><normal>0 0 1</normal><size>100 100</size></plane>
          </geometry>
          <material>
            <ambient>0.8 0.8 0.8 1</ambient>
            <diffuse>0.8 0.8 0.8 1</diffuse>
          </material>
        </visual>
      </link>
    </model>
"""

ROBOT_TEMPLATE = """
    <model name="{rid}">
      <pose>{x} {y} 0 0 0 {yaw}</pose>

      <link name="base_link">
        <pose>0 0 0.010 0 0 0</pose>
        <inertial>
          <mass>8.2573504e-01</mass>
          <inertia>
            <ixx>2.2124416e-03</ixx><ixy>-1.2294101e-05</ixy><ixz>3.4938785e-05</ixz>
            <iyy>2.1193702e-03</iyy><iyz>-5.0120904e-06</iyz>
            <izz>2.0064271e-03</izz>
          </inertia>
        </inertial>
        <visual name="visual_body">
          <pose>-0.032 0 0.070 0 0 0</pose>
          <geometry><box><size>0.140 0.140 0.143</size></box></geometry>
          <material>
            <ambient>{color}</ambient>
            <diffuse>{color}</diffuse>
          </material>
        </visual>
        <collision name="collision_body">
          <pose>-0.032 0 0.070 0 0 0</pose>
          <geometry><box><size>0.140 0.140 0.143</size></box></geometry>
        </collision>
      </link>

      <link name="wheel_left_link">
        <pose>0.0 0.080 0.033 -1.5707963 0 0</pose>
        <inertial>
          <mass>2.8498940e-02</mass>
          <inertia>
            <ixx>1.1175580e-05</ixx><ixy>-4.2369783e-11</ixy><ixz>-5.9381719e-09</ixz>
            <iyy>1.1192413e-05</iyy><iyz>-1.4400107e-11</iyz>
            <izz>2.0712558e-05</izz>
          </inertia>
        </inertial>
        <visual name="visual">
          <geometry><cylinder><radius>0.033</radius><length>0.018</length></cylinder></geometry>
          <material><ambient>0.1 0.1 0.1 1</ambient><diffuse>0.1 0.1 0.1 1</diffuse></material>
        </visual>
        <collision name="collision">
          <surface><friction><ode><mu>1.0</mu><mu2>0.5</mu2></ode></friction></surface>
          <geometry><cylinder><radius>0.033</radius><length>0.018</length></cylinder></geometry>
        </collision>
      </link>

      <link name="wheel_right_link">
        <pose>0.0 -0.080 0.033 -1.5707963 0 0</pose>
        <inertial>
          <mass>2.8498940e-02</mass>
          <inertia>
            <ixx>1.1175580e-05</ixx><ixy>-4.2369783e-11</ixy><ixz>-5.9381719e-09</ixz>
            <iyy>1.1192413e-05</iyy><iyz>-1.4400107e-11</iyz>
            <izz>2.0712558e-05</izz>
          </inertia>
        </inertial>
        <visual name="visual">
          <geometry><cylinder><radius>0.033</radius><length>0.018</length></cylinder></geometry>
          <material><ambient>0.1 0.1 0.1 1</ambient><diffuse>0.1 0.1 0.1 1</diffuse></material>
        </visual>
        <collision name="collision">
          <surface><friction><ode><mu>1.0</mu><mu2>0.5</mu2></ode></friction></surface>
          <geometry><cylinder><radius>0.033</radius><length>0.018</length></cylinder></geometry>
        </collision>
      </link>

      <link name="caster_back_link">
        <pose>-0.081 0 0.033 0 0 0</pose>
        <inertial>
          <mass>0.005</mass>
          <inertia><ixx>0.001</ixx><ixy>0</ixy><ixz>0</ixz><iyy>0.001</iyy><iyz>0</iyz><izz>0.001</izz></inertia>
        </inertial>
        <visual name="visual">
          <geometry><sphere><radius>0.033</radius></sphere></geometry>
          <material><ambient>0.3 0.3 0.3 1</ambient><diffuse>0.3 0.3 0.3 1</diffuse></material>
        </visual>
        <collision name="collision">
          <surface><friction><ode><mu>0.0</mu><mu2>0.0</mu2></ode></friction></surface>
          <geometry><sphere><radius>0.033</radius></sphere></geometry>
        </collision>
      </link>

      <joint name="wheel_left_joint" type="revolute">
        <parent>base_link</parent>
        <child>wheel_left_link</child>
        <axis>
          <xyz>0 0 1</xyz>
          <limit><lower>-1.79769e+308</lower><upper>1.79769e+308</upper></limit>
          <dynamics><damping>0.01</damping><friction>0.01</friction></dynamics>
        </axis>
      </joint>

      <joint name="wheel_right_joint" type="revolute">
        <parent>base_link</parent>
        <child>wheel_right_link</child>
        <axis>
          <xyz>0 0 1</xyz>
          <limit><lower>-1.79769e+308</lower><upper>1.79769e+308</upper></limit>
          <dynamics><damping>0.01</damping><friction>0.01</friction></dynamics>
        </axis>
      </joint>

      <joint name="caster_back_joint" type="ball">
        <parent>base_link</parent>
        <child>caster_back_link</child>
      </joint>

      <plugin filename="gz-sim-diff-drive-system" name="gz::sim::systems::DiffDrive">
        <left_joint>wheel_left_joint</left_joint>
        <right_joint>wheel_right_joint</right_joint>
        <wheel_separation>0.160</wheel_separation>
        <wheel_radius>0.033</wheel_radius>
        <odom_publish_frequency>10</odom_publish_frequency>
        <topic>/{rid}/cmd_vel</topic>
        <odom_topic>/{rid}/odom</odom_topic>
        <tf_topic>/tf</tf_topic>
        <frame_id>{rid}/odom</frame_id>
        <child_frame_id>{rid}/base_footprint</child_frame_id>
      </plugin>

      <plugin filename="gz-sim-joint-state-publisher-system" name="gz::sim::systems::JointStatePublisher">
        <topic>/{rid}/joint_states</topic>
      </plugin>
    </model>
"""

WORLD_FOOTER = """
  </world>
</sdf>
"""


def color_to_rviz(color: str) -> str:
    r, g, b = (float(c) for c in color.split()[:3])
    return f"{int(r * 255)}; {int(g * 255)}; {int(b * 255)}"


def generate_world(robots: list[dict[str, Any]]) -> str:
    body = "".join(
        ROBOT_TEMPLATE.format(
            rid=r["id"],
            x=r["spawn"]["x"],
            y=r["spawn"]["y"],
            yaw=r["spawn"].get("yaw", 0.0),
            color=r["color"],
        )
        for r in robots
    )
    return WORLD_HEADER + body + WORLD_FOOTER


def generate_rviz(robots: list[dict[str, Any]]) -> str:
    displays: list[dict[str, Any]] = [
        {"Class": "rviz_default_plugins/Grid", "Name": "Grid", "Enabled": True,
         "Plane Cell Count": 20, "Cell Size": 1.0},
        {"Class": "rviz_default_plugins/TF", "Name": "TF", "Enabled": True,
         "Show Names": True, "Marker Scale": 3.0},
    ]
    for r in robots:
        rid = r["id"]
        displays.append({
            "Class": "rviz_default_plugins/RobotModel",
            "Name": f"{rid} model",
            "Enabled": True,
            "Description Source": "Topic",
            "Description Topic": {
                "Value": f"/{rid}/robot_description",
                "Durability Policy": "Transient Local",
                "Reliability Policy": "Reliable",
                "Depth": 1,
            },
            "TF Prefix": rid,
        })
        displays.append({
            "Class": "rviz_default_plugins/Odometry",
            "Name": f"{rid} odom",
            "Enabled": True,
            "Topic": {
                "Value": f"/{rid}/odom",
                "Reliability Policy": "Best Effort",
                "Durability Policy": "Volatile",
                "Depth": 5,
            },
            "Keep": 200,
            "Position Tolerance": 0.05,
            "Angle Tolerance": 0.1,
            "Shape": {"Value": "Arrow", "Color": color_to_rviz(r["color"]),
                      "Shaft Length": 0.15, "Shaft Radius": 0.01,
                      "Head Length": 0.05, "Head Radius": 0.02, "Alpha": 1.0},
            "Covariance": {"Value": False},
        })
    cfg = {
        "Panels": [
            {"Class": "rviz_common/Displays", "Name": "Displays"},
            {"Class": "rviz_common/Views", "Name": "Views"},
        ],
        "Visualization Manager": {
            "Class": "",
            "Displays": displays,
            "Global Options": {"Fixed Frame": "world", "Frame Rate": 30,
                               "Background Color": "48; 48; 48"},
            "Views": {
                "Current": {"Class": "rviz_default_plugins/Orbit", "Name": "Current View",
                            "Distance": 12.0, "Pitch": 1.0, "Yaw": 1.57,
                            "Focal Point": {"X": 0.0, "Y": 1.0, "Z": 0.0}},
            },
        },
    }
    header = "# AUTO-GENERATED by scripts/generate_fleet.py from config/fleet.yaml. Do not edit.\n"
    return header + yaml.safe_dump(cfg, sort_keys=False, default_flow_style=False)


def main() -> None:
    fleet = yaml.safe_load((ROOT / "config" / "fleet.yaml").read_text())
    robots = fleet["robots"]
    if not robots:
        raise SystemExit("fleet.yaml defines no robots")

    world_path = ROOT / "worlds" / "fleet.sdf"
    rviz_path = ROOT / "config" / "fleet.rviz"
    world_path.write_text(generate_world(robots))
    rviz_path.write_text(generate_rviz(robots))
    print(f"Generated {world_path.relative_to(ROOT)} and {rviz_path.relative_to(ROOT)} "
          f"for {len(robots)} robots: {', '.join(r['id'] for r in robots)}")


if __name__ == "__main__":
    main()
